#!/bin/env python3
import json
import colorsys
import re


def hsl_to_hex(hsl_str):
    # "hsl(H, S%, L%)" を抽出
    m = re.match(r"hsl\((\d+),\s*(\d+)%?,\s*(\d+)%?\)", hsl_str)
    if not m:
        raise ValueError(f"Invalid HSL: {hsl_str}")
    h, s, l = map(int, m.groups())

    # colorsys 用に正規化
    h = h / 360.0
    s = s / 100.0
    l = l / 100.0

    r, g, b = colorsys.hls_to_rgb(h, l, s)
    r, g, b = [int(round(x * 255)) for x in (r, g, b)]

    return "#{:02x}{:02x}{:02x}".format(r, g, b)


def generate_nvim(palette: dict[str, str]):
    buf = 'local U = require("yoru.utils.color")\n\n'
    buf += "local C = {\n"
    buf += f'  none = "NONE",\n'
    for color in palette.keys():
        buf += f'  {color} = "{palette[color]}",\n'
    buf += "}\n"
    buf += """
C.red_light = U.mix_hex(C.bg, C.red, 0.1)
C.orange_light = U.mix_hex(C.bg, C.orange, 0.1)
C.yellow_light = U.mix_hex(C.bg, C.yellow, 0.1)
C.green_light = U.mix_hex(C.bg, C.green, 0.1)
C.blue_light = U.mix_hex(C.bg, C.blue, 0.1)
C.purple_light = U.mix_hex(C.bg, C.purple, 0.1)

return C
"""

    with open("lua/yoru/palette.lua", "w", encoding="utf-8") as f:
        f.write(buf)


def generate_alacritty(palette: dict[str, str]):
    buf = f"""[colors.primary]
background = "{palette["bg"]}"
foreground = "{palette["fg"]}"

[colors.cursor]
text = "{palette["black"]}"
cursor = "{palette["white"]}"

[colors.selection]
text = "{palette["black"]}"
background = "{palette["white"]}"

[colors.normal]
black = "{palette["black"]}"
red = "{palette["red"]}"
green = "{palette["green"]}"
yellow = "{palette["yellow"]}"
blue = "{palette["blue"]}"
magenta = "{palette["purple"]}"
cyan = "{palette["cyan"]}"
white = "{palette["white"]}"

[colors.bright]
black = "{palette["black"]}"
red = "{palette["red"]}"
green = "{palette["green"]}"
yellow = "{palette["yellow"]}"
blue = "{palette["blue"]}"
magenta = "{palette["purple"]}"
cyan = "{palette["cyan"]}"
white = "{palette["white"]}"
"""

    with open("extras/alacritty/yoru.toml", "w", encoding="utf-8") as f:
        f.write(buf)


def generate_windows_terminal(palette: dict[str, str]):
    buf = (
        "{"
        + f"""
  "background": "{palette["bg"]}",
  "black": "{palette["black"]}",
  "blue": "{palette["blue"]}",
  "brightBlack": "{palette["black"]}",
  "brightBlue": "{palette["blue"]}",
  "brightCyan": "{palette["cyan"]}",
  "brightGreen": "{palette["green"]}",
  "brightPurple": "{palette["purple"]}",
  "brightRed": "{palette["red"]}",
  "brightWhite": "{palette["white"]}",
  "brightYellow": "{palette["yellow"]}",
  "cursorColor": "{palette["white"]}",
  "cyan": "{palette["cyan"]}",
  "foreground": "{palette["fg"]}",
  "green": "{palette["green"]}",
  "name": "Yoru",
  "purple": "{palette["purple"]}",
  "red": "{palette["red"]}",
  "selectionBackground": "{palette["selection"]}",
  "white": "{palette["white"]}",
  "yellow": "{palette["yellow"]}"
"""
        + "}\n"
    )

    with open("extras/windows-terminal/yoru.json", "w", encoding="utf-8") as f:
        f.write(buf)


with open("./palette.json", "r", encoding="utf-8") as f:
    data = json.load(f)

palette = {k: hsl_to_hex(v) for k, v in data.items()}

generate_nvim(palette)
generate_alacritty(palette)
generate_windows_terminal(palette)
