local M = {}

function M.get()
  local C = require("yoru.palette")

  return {
    Cursor = { fg = C.fg },
    CursorLine = { bg = C.bg_light },
    LineNr = { fg = C.black },
    CursorLineNr = { fg = C.orange },
    EndOfBuffer = { fg = C.black },
    WinSeparator = { fg = C.black },
    FloatBorder = { fg = C.black },
    Visual = { bg = C.selection },
    Whitespace = { fg = C.white },
    CurSearch = { fg = C.fg, bg = C.orange },
    Search = { fg = C.fg, bg = C.blue },
    TabLine = { bg = C.bg_light },
    TabLineSel = { fg = C.fg, bg = C.bg },

    Normal = { fg = C.fg, bg = C.none },
    NormalFloat = { fg = C.fg, bg = C.none },
    Underlined = { fg = C.green },
    Ignore = { fg = C.blue },
    Error = { link = "DiagnosticError" },
    Todo = { link = "DiagnosticInfo" },

    Comment = { fg = C.white },
    String = { fg = C.green },
    Character = { fg = C.green },
    Constant = { fg = C.orange },
    Number = { fg = C.cyan },
    Boolean = { fg = C.cyan },
    Identifier = { fg = C.fg },
    Function = { fg = C.blue },
    Keyword = { fg = C.purple },
    Type = { fg = C.yellow },
    Special = { fg = C.yellow },
    Tag = { fg = C.purple },
    Delimiter = { fg = C.white },
    Debug = { fg = C.yellow },
    Directory = { fg = C.blue },

    Added = { fg = C.green },
    Changed = { fg = C.blue },
    Removed = { fg = C.red },

    Pmenu = { fg = C.fg, bg = C.black },
    PmenuSel = { fg = C.fg, bg = C.selection },
    Notifybg = { bg = C.selection },

    DiagnosticError = { fg = C.red },
    DiagnosticWarn = { fg = C.yellow },
    DiagnosticInfo = { fg = C.blue },
    DiagnosticHint = { fg = C.purple },
    DiagnosticOk = { fg = C.green },
    DiagnosticUnderlineError = { sp = C.red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = C.yellow, undercurl = true },
    DiagnosticUnderlineInfo = { sp = C.blue, undercurl = true },
    DiagnosticUnderlineHint = { sp = C.purple, undercurl = true },
    DiagnosticUnderlineOk = { sp = C.green, undercurl = true },

    ["@variable"] = { link = "Identifier" },
    ["@constant"] = { link = "Constant" },
    ["@module"] = { fg = C.yellow },
    ["@string"] = { link = "String" },
    ["@string.special.url"] = { link = "String" },
    ["@character"] = { link = "Character" },
    ["@boolean"] = { link = "Boolean" },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { link = "Keyword" },
    ["@property"] = { fg = C.red },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { link = "Function" },
    ["@keyword"] = { link = "Keyword" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { link = "Bracket" },
    ["@punctuation.special"] = { link = "Special" },
    ["@comment"] = { link = "Comment" },
    ["@comment.error"] = { link = "DiagnosticError" },
    ["@comment.warning"] = { link = "DiagnosticWarn" },
    ["@comment.todo"] = { link = "DiagnosticInfo" },
    ["@comment.note"] = { link = "DiagnosticHint" },
    ["@markup.heading"] = { fg = C.red, bold = true },
    ["@markup.heading.1"] = { fg = C.red, bold = true },
    ["@markup.heading.2"] = { fg = C.orange, bold = true },
    ["@markup.heading.3"] = { fg = C.yellow, bold = true },
    ["@markup.heading.4"] = { fg = C.green, bold = true },
    ["@markup.heading.5"] = { fg = C.blue, bold = true },
    ["@markup.heading.6"] = { fg = C.purple, bold = true },
    ["@markup.link.url"] = { fg = C.blue },
    ["@markup.link.label.markdown_inline"] = { fg = C.blue },
    ["@diff.plus"] = { link = "Added" },
    ["@diff.minus"] = { link = "Removed" },
    ["@diff.delta"] = { link = "Changed" },
    ["@tag"] = { link = "Tag" },
    ["@tag.attribute"] = { link = "@property" },
    ["@lsp.type.namespace"] = { link = "Module" },

    OilHidden = { fg = C.fg },
    OilDir = { link = "Directory" },
    OilDirHidden = { link = "OilHidden" },
    OilFile = { fg = C.fg },

    MiniIconsAzure = { fg = C.blue },
    MiniIconsBlue = { fg = C.blue },
    MiniIconsCyan = { fg = C.cyan },
    MiniIconsGreen = { fg = C.green },
    MiniIconsGrey = { fg = C.white },
    MiniIconsOrange = { fg = C.orange },
    MiniIconsPurple = { fg = C.purple },
    MiniIconsRed = { fg = C.red },
    MiniIconsYellow = { fg = C.yellow },

    BufferOffset = { bg = C.bg_dark, fg = C.fg },
    BufferCurrent = { bg = C.none, fg = C.fg },
    BufferCurrentIndex = { bg = C.none, fg = C.blue },
    BufferCurrentMod = { bg = C.none, fg = C.yellow },
    BufferCurrentSign = { bg = C.none, fg = C.bg },
    BufferCurrentTarget = { bg = C.none, fg = C.red },
    BufferVisible = { bg = C.bg_light, fg = C.fg },
    BufferVisibleIndex = { bg = C.bg_light, fg = C.blue },
    BufferVisibleMod = { bg = C.bg_light, fg = C.yellow },
    BufferVisibleSign = { bg = C.bg_light, fg = C.bg },
    BufferVisibleTarget = { bg = C.bg_light, fg = C.red },
    BufferInactive = { bg = C.bg_light, fg = C.black },
    BufferInactiveIndex = { bg = C.bg_light, fg = C.blue },
    BufferInactiveMod = { bg = C.bg_light, fg = C.yellow },
    BufferInactiveSign = { bg = C.bg_light, fg = C.bg },
    BufferInactiveTarget = { bg = C.bg_light, fg = C.red },
    BufferTabpages = { bg = C.bg_light, fg = C.bg },
    BufferTabpage = { bg = C.bg_light, fg = C.blue },

    SnacksDashboardDesc = { fg = C.blue },
    SnacksDashboardFooter = { fg = C.green },
    SnacksDashboardHeader = { fg = C.green },
    SnacksDashboardIcon = { fg = C.blue },
    SnacksDashboardKey = { fg = C.red },
    SnacksDashboardSpecial = { fg = C.purple },
    SnacksDashboardDir = { fg = C.yellow },
    SnacksDashboardFile = { fg = C.yellow },
  }
end

return M
